import React from "react";
import './Tech.css'
const Tech = () => {
  return (
    <div className="container-skills">
      <h1>
        Habilidades
      </h1>
      <div className="skills">
        <li>
          <img
            src="https://mpng.subpng.com/20190627/ttx/kisspng-javascript-computer-icons-scalable-vector-graphics-list-of-javascript-enhancements-fandom-developers-5d145895b06253.7824611015616144857225.jpg"
            alt="img"
          />
          JavaScript
        </li>
        <li>
          <img
            src="https://cdn.worldvectorlogo.com/logos/mongodb-icon-1.svg"
            alt="img"
          />
          MongoDB
        </li>
        <li>
          <img
            src="https://w7.pngwing.com/pngs/441/460/png-transparent-postgresql-plain-wordmark-logo-icon.png"
            alt="img"
          />
          PostgreSQL
        </li>
        <li>
          <img
            src="https://seeklogo.com/images/N/nodejs-logo-FBE122E377-seeklogo.com.png"
            alt="img"
          />
          Node.js
        </li>
        <li>
          <img
            src="https://w7.pngwing.com/pngs/925/447/png-transparent-express-js-node-js-javascript-mongodb-node-js-text-trademark-logo.png"
            alt="img"
          />
          Express.js
        </li>
        <li>
          <img
            src="https://seeklogo.com/images/C/css-3-logo-023C1A7171-seeklogo.com.png"
            alt="img"
          />
          CSS
        </li>
        <li>
          <img
            src="https://camo.githubusercontent.com/58e35d08b53ec029f0e3e587a28a6f65777d352f797add843d153a0db60b9d7d/68747470733a2f2f692e696d6775722e636f6d2f79764559686e5a2e706e67"
            alt="img"
            />
            Sequelize
        </li>
        <li>
          <img
            src="https://seeklogo.com/images/R/react-logo-7B3CE81517-seeklogo.com.png"
            alt="img"
            />
            React
        </li>
        <li>
          <img
            src="https://img.favpng.com/6/2/11/redux-react-javascript-freecodecamp-npm-png-favpng-6F2x50visKuC0trBQ0952Cm1E_t.jpg"
            alt="img"
            />
            Redux
        </li>
        <li>
          <img
            src="https://upload.wikimedia.org/wikipedia/commons/thumb/3/3f/Git_icon.svg/1200px-Git_icon.svg.png"
            alt="img"
            />
            Git
        </li>
        <li>
          <img
            src="https://1000marcas.net/wp-content/uploads/2020/02/GitHub-Simbolo.jpg"
            alt="img"
            />
            GitHub
        </li>
        <li>
          <img
            src="https://www.seekpng.com/png/detail/80-803527_html5-css3-and-javascript-logos-html5-logo-png.png"
            alt="img"
            />
            HTML5
        </li>
      </div>
    </div>
  );
};

export default Tech;
