export const techs = [
  { name: 'JavaScript', icons: '/icons/javascript-svgrepo-com.svg' },
  { name: 'React', icons: '/icons/react-svgrepo-com.png' },
  { name: 'Node', icons: '/icons/nodejs-icon-logo-svgrepo-com.png' },
  { name: 'Tailwind', icons: '/icons/tailwind-svgrepo-com.png' },
  { name: 'CSS', icons: '/icons/css-3-svgrepo-com.svg' },
  { name: 'Express', icons: '/icons/express-svgrepo-com.png' },
  { name: 'MongoDB', icons: '/icons/mongodb-svgrepo-com.svg' },
  { name: 'Git', icons: '/icons/git-svgrepo-com.svg' },
  { name: 'Redux', icons: '/icons/redux-svgrepo-com.png' },
  { name: 'PostgreSQL', icons: '/icons/postgresql-svgrepo-com.svg' },
  { name: 'GitHub', icons: '/icons/github-svgrepo-com.svg' },
  { name: 'Next', icons: '/icons/next-js-svgrepo-com.svg' },
  { name: 'Zustand', icons: '/icons/zustand.webp' },
]
